[package]
name = "dping"
version = "0.1.0"
edition = "2021"

[dependencies]
ping = "0.5.2"
console = "0.15.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.120"
dialoguer = "0.9"
